Controllers/ProductosController.cs
using AccesoDatos;
using Entidades;
using PracticoMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticoMVC.Controllers
{
    public class ProductosController : Controller
    {
        // obtengo el listado de productos activos (stock)
        public ActionResult ConsultaProducto()
        {
            ProductosQuerys pq = new ProductosQuerys();
            List<Productos> prod = new List<Productos>();
            MarcasQuerys mq = new MarcasQuerys();
            List<Marcas> mar = new List<Marcas>();
            mar = mq.GetMarcas();
            prod = pq.GetProductos();
            ViewBag.Lista = prod;
            ViewBag.ListaMarcas = mar;

            return View();
        }

        // preparo el formulario para registrar con los selects necesarios
        [HttpGet]
        public ActionResult RegistroProducto()
        {
            MarcasQuerys mq = new MarcasQuerys();
            List<Marcas> marcas = new List<Marcas>();
            marcas = mq.GetMarcas();
            ViewBag.Lista = marcas;

            return View();
        }

        // valido el formulario para proceder al registro
        [HttpPost]
        public ActionResult RegistroProducto(ProductoModelo modelo)
        {
            int exito = 2; // es el valor cuando el modelo no es valido
            if (ModelState.IsValid)
            {
                try
                {
                    ProductosQuerys pq = new ProductosQuerys();
                    Productos entidad = new Productos();
                    entidad.Nombre = modelo.Nombre;
                    entidad.Descripcion = modelo.Descripcion;
                    entidad.IdMarca = modelo.IdMarca;
                    entidad.Activo = modelo.Activo;
                    entidad.PrecioUnitario = modelo.PrecioUnitario;
                    entidad.UrlImange = modelo.UrlImange;
                    var existe = pq.ExisteNombre(entidad.Nombre); //busco el producto por nombre
                    if(existe == true) //si el producto existe
                    {
                        exito = 0;
                        ViewBag.Class = "alert alert-warning";
                        ViewBag.Message = "El producto que intenta registrar ya existe.";
                    }
                    else //si no existe, continuo con la inserción
                    {
                        var obj = pq.InsertProducto(entidad); //inserto el producto
                        if (obj == true) //si se pudo insertar
                        {
                            exito = 1;
                            ViewBag.Class = "alert alert-success";
                            ViewBag.Message = "Producto registrado correctamente!";
                        }
                        else //si no se pudo insertar, el error está en el método o la conexión a la DB
                        {
                            exito = 0;
                            ViewBag.Class = "alert alert-danger";
                            ViewBag.Message = "Oops! Algo ha ocurrido!";
                        }
                    }
                }
                catch (Exception e)
                {
                    throw e;
                }
            }

            //maneja la vista, según la variable éxito
            if (exito == 1)
            {
                ModelState.Clear();

                MarcasQuerys mq = new MarcasQuerys();
                List<Marcas> marcas = new List<Marcas>();
                marcas = mq.GetMarcas();
                ViewBag.Lista = marcas;

                return View();
            }
            else
            {
                if (exito == 0)
                {
                    ModelState.Clear();

                    MarcasQuerys mq = new MarcasQuerys();
                    List<Marcas> marcas = new List<Marcas>();
                    marcas = mq.GetMarcas();
                    ViewBag.Lista = marcas;

                    return View();
                }
                else
                {
                    MarcasQuerys mq = new MarcasQuerys();
                    List<Marcas> marcas = new List<Marcas>();
                    marcas = mq.GetMarcas();
                    ViewBag.Lista = marcas;
                    ViewBag.Class = "alert alert-warning";
                    ViewBag.Message = "Faltan datos por ingresar! Controle todos los campos que son obligatorios.";

                    return View(modelo);
                }
            }
        }

        // preparo el formulario para eliminar
        [HttpGet]
        public ActionResult EliminaProducto(int codigo = 0)
        {
            ProductoModelo model = new ProductoModelo();
            Productos entidad = new Productos();
            List<Productos> datosProducto = new List<Productos>();
            entidad.Codigo = codigo;
            ProductosQuerys pq = new ProductosQuerys();
            datosProducto = pq.ProductoPorCodigo(entidad.Codigo);

            MarcasQuerys mq = new MarcasQuerys();
            List<Marcas> marcas = new List<Marcas>();
            marcas = mq.GetMarcas();
            ViewBag.Lista = marcas;

            foreach (var datos in datosProducto)
            {
                model.Codigo = datos.Codigo;
                model.Nombre = datos.Nombre;
                model.Descripcion = datos.Descripcion;
                model.IdMarca = datos.IdMarca;

                ViewBag.MarcaSeleccionada = model.IdMarca;
                
                model.PrecioUnitario = datos.PrecioUnitario;
                model.Activo = datos.Activo;
                if (string.IsNullOrEmpty(datos.UrlImange))
                {
                    model.UrlImange = "Este producto no tiene URL, de imagen, asociada.";
                }
                else
                {
                    model.UrlImange = datos.UrlImange;
                }
            }

            return View(model);
        }

        // valido el formulario para proceder con la eliminación
        [HttpPost]
        public ActionResult EliminaProducto(ProductoModelo modelo)
        {
            int exito = 2; // es el valor cuando el modelo no es valido

            MarcasQuerys mq = new MarcasQuerys();

            if (ModelState.IsValid) //si se cumplen todas las validaciones
            {
                try
                {
                    ProductosQuerys pq = new ProductosQuerys();
                    Productos entidad = new Productos();
                    entidad.Codigo = modelo.Codigo;
                    var obj = pq.DeleteProducto(entidad.Codigo);
                    if (obj == true)
                    {
                        exito = 1;
                        ViewBag.Class = "alert alert-success";
                        ViewBag.Message = "Producto eliminado correctamente!";
                        ViewBag.Exito = 1;

                    }
                    else //si no se pudo eliminar, el error está en el método o la conexión a la DB
                    {
                        exito = 0;
                        ViewBag.Class = "alert alert-danger";
                        ViewBag.Message = "Oops! Algo ha ocurrido!";
                        ViewBag.Exito = 0;

                    }

                }
                catch (Exception e)
                {
                    throw e;
                }
            }

            //manejo la vista, según el valor de la variable exito
            if (exito == 1)
            {
                ModelState.Clear();

                List<Marcas> marcas = new List<Marcas>();
                marcas = mq.GetMarcas();
                ViewBag.Lista = marcas;

                return View();
            }
            else
            {
                if (exito == 0)
                {
                    ModelState.Clear();

                    List<Marcas> marcas = new List<Marcas>();
                    marcas = mq.GetMarcas();
                    ViewBag.Lista = marcas;

                    return View();
                }
                else
                {
                    List<Marcas> marcas = new List<Marcas>();
                    marcas = mq.GetMarcas();
                    ViewBag.Lista = marcas;

                    ViewBag.Class = "alert alert-warning";
                    ViewBag.Message = "Faltan datos por ingresar! Controle todos los campos que son obligatorios.";

                    return View(modelo);
                }
            }
        }

        //preparo el formulario para editar
        [HttpGet]
        public ActionResult EditarProducto(int codigo = 0)
        {
            ProductoModelo model = new ProductoModelo();
            Productos entidad = new Productos();
            List<Productos> datosProducto = new List<Productos>();
            entidad.Codigo = codigo;
            ProductosQuerys pq = new ProductosQuerys();
            datosProducto = pq.ProductoPorCodigo(entidad.Codigo);

            MarcasQuerys mq = new MarcasQuerys();
            List<Marcas> marcas = new List<Marcas>();
            marcas = mq.GetMarcas();
            ViewBag.Lista = marcas;

            foreach (var datos in datosProducto)
            {
                model.Codigo = datos.Codigo;
                model.Nombre = datos.Nombre;
                model.Descripcion = datos.Descripcion;
                model.IdMarca = datos.IdMarca;

                ViewBag.MarcaSeleccionada = model.IdMarca;

                model.PrecioUnitario = datos.PrecioUnitario;
                model.Activo = datos.Activo;
                if (string.IsNullOrEmpty(datos.UrlImange))
                {
                    model.UrlImange = "Este producto no tiene URL, de imagen, asociada.";
                }
                else
                {
                    model.UrlImange = datos.UrlImange;
                }
            }

            return View(model);
        }

Views/Productos/ConsultaProducto.cshtml
@{int fila = 1; }

@{
    ViewBag.Title = "Consulta de Productos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .miActionLink:hover {
        color: white
    }

    .miActionLink {
        color: white
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <button class="btn btn-primary btn-success" title="Ingresar un elemento nuevo" style="position: absolute; right: 0;" type="button"><i class="fas fa-newspaper"></i> @Html.ActionLink("Nuevo", "RegistroProducto", "Productos", new { @class = "miActionLink" }) </button>
        <br />
        <div class="table-responsive">
            <h4> Listado de Productos </h4>
            <hr />
            <table class="table table-borderless table-striped table-earning">
                <thead>
                    <tr style="text-align: center;">
                        <td> <b>#</b> </td>
                        <td> <b>Código</b> </td>
                        <td> <b>Nombre</b> </td>
                        <td> <b>Descripción</b> </td>
                        <td> <b>Marca</b> </td>
                        <td> <b>Precio Unitario</b> </td>
                        <td> <b>Imagen</b> </td>
                        <td> <b>Acciones</b> </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var prod in ViewBag.Lista)
                    {
                        <tr>
                            <td>@fila </td>
                            <td>@prod.Codigo </td>
                            <td>@prod.Nombre </td>
                            <td>@prod.Descripcion </td>
                            @foreach (var marca in ViewBag.ListaMarcas)
                            {
                                if (prod.IdMarca == marca.Id)
                                {
                                    <td>@marca.Nombre</td>
                                }
                            }
                            <td>$ @prod.PrecioUnitario </td>
                            <td><img align="middle" style="width:auto;height:auto" src="@prod.UrlImange" alt="@prod.Nombre"></td>
                            <td>
                                <button title="Editar" class="btn btn-primary btn-info" onclick='window.location="@Url.Action("EditarProducto","Productos",new { codigo = prod.Codigo })"' type="button" name="Editar" id="Editar"><i class="fas fa-edit"></i></button>
                                <button title="Eliminar" class="btn btn-primary btn-danger" onclick='window.location="@Url.Action("EliminaProducto","Productos",new { codigo = prod.Codigo })"' type="button" name="Eliminar" id="Elimiar"><i class="fas fa-crosshairs"></i></button>
                            </td>
                        </tr>
                        fila++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-12">
        <button class="btn btn-primary btn-warning" title="Ir Hacia Arriba" style="position: absolute; right: 0;" type="button" onclick="topFunction()"><i class="fas fa-arrow-alt-circle-up"></i></button>
    </div>
</div>

<script>
    function topFunction() {
        document.body.scrollTop = 0; // For Safari
        document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
    }
</script>

Views/Productos/EditarProducto.cshtml
@model PracticoMVC.Models.ProductoModelo

@{
    ViewBag.Title = "Edición de Productos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        @if (ViewBag.Message != null)
        {
            <div class="row" style="margin-top:2%;">
                <div class="col-md-8">
                    <div class="@ViewBag.Class" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-lg-12">
                <button class="btn btn-primary btn-warning" title="Volver atrás" style="position: absolute; right: 0;" onclick='window.location="@Url.Action("ConsultaProducto","Productos")"' type="button"><i class="fas fa-arrow-alt-circle-left"></i></button>
                <br />
                <br />
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4> Edición de Productos </h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("EditarProducto", "Productos", FormMethod.Post))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control", @placeholder = "Aquí debe autocompletarse el código de producto...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @placeholder = "Aquí debe autocompletarse el nombre de producto...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @placeholder = "Aquí debe autocompletarse la descripción de producto...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.IdMarca, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                <select name="IdMarca" id="IdMarca" class="form-control">
                                    <option value="">SELECCIONE UNA MARCA...</option>
                                    @if (ViewBag.Exito != null)  //si fuese null, significa que los datos deben completarse. Sino, significa que ya interactuamos con la app y se obtuvo algún resultado
                                    {
                                        <option value="">AQUÍ DEBE AUTOCOMPLETARSE LA MARCA DE PRODUCTO...</option>
                                    }
                                    else
                                    {
                                        foreach (var marca in ViewBag.Lista)
                                        {
                                            if (Model.IdMarca == marca.Id)
                                            {
                                                <option value="@marca.Id" selected>@marca.Nombre</option>
                                            }
                                            else
                                            {
                                                <option value="@marca.Id">@marca.Nombre</option>
                                            }
                                        }
                                    }
                                </select>
                                @Html.ValidationMessageFor(model => model.IdMarca, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                <select name="Activo" id="Activo" class="form-control">
                                    <option value="">SELECCIONE SU ESTADO...</option>
                                    @if (ViewBag.Exito != null) //si fuese null, significa que los datos deben completarse. Sino, significa que ya interactuamos con la app y se obtuvo algún resultado
                                    {
                                        <option value="">AQUÍ DEBE AUTOCOMPLETARSE EL ESTADO DE PRODUCTO...</option>
                                    }
                                    else
                                    {
                                        if (Model.Activo == 1)
                                        {
                                            <option value="1" selected>HABILITADO</option>
                                            <option value="0">DESHABILITADO</option>
                                        }
                                        else
                                        {
                                            if (Model.Activo == 0)
                                            {
                                                <option value="1">HABILITADO</option>
                                                <option value="0" selected>DESHABILITADO</option>
                                            }
                                        }
                                    }
                                </select>
                                @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.PrecioUnitario, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @if (ViewBag.Exito != null)
                                {
                                    @Html.EditorFor(model => model.PrecioUnitario, new { htmlAttributes = new { @type = "number", @class = "form-control", @placeholder = "Aquí debe autocompletarse el precio unitario de producto...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                }
                                else
                                {
                                    @Html.EditorFor(model => model.PrecioUnitario, new { htmlAttributes = new { @type = "number", @Value = Model.PrecioUnitario, @class = "form-control", @placeholder = "Aquí debe autocompletarse el precio unitario de producto...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                }
                                @Html.ValidationMessageFor(model => model.PrecioUnitario, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.UrlImange, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.UrlImange, new { htmlAttributes = new { @type = "url", @class = "form-control", @placeholder = "Aquí debe autocompletarse la URL de imagen de producto..." } })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col-lg-12">
                                <input type="submit" style="margin-left:45%" class="btn btn-primary" name="Modificar" id="Modificar" value="Modificar" />
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

Views/Productos/RegistroProducto.cshtml
@model PracticoMVC.Models.ProductoModelo

@{
    ViewBag.Title = "Registro de Productos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        @if (ViewBag.Message != null)
        {
            <div class="row" style="margin-top:2%;">
                <div class="col-md-8">
                    <div class="@ViewBag.Class" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-lg-12">
                <button class="btn btn-primary btn-warning" title="Volver atrás" style="position: absolute; right: 0;" onclick='window.location="@Url.Action("ConsultaProducto","Productos")"' type="button"><i class="fas fa-arrow-alt-circle-left"></i></button>
                <br />
                <br />
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4> Registro de Productos </h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("RegistroProducto", "Productos", FormMethod.Post))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese un nombre de producto...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese una descripción de producto...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.IdMarca, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                <select name="IdMarca" id="IdMarca" class="form-control">
                                    <option value="">SELECCIONE UNA MARCA...</option>
                                    @foreach (var marca in ViewBag.Lista)
                                    {
                                        <option value="@marca.Id">@marca.Nombre</option>
                                    }
                                </select>
                                @Html.ValidationMessageFor(model => model.IdMarca, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                <select name="Activo" id="Activo" class="form-control">
                                        <option value="">SELECCIONE SU ESTADO...</option>
                                        <option value="1">HABILITADO</option>
                                        <option value="0">DESHABILITADO</option>
                                </select>
                                @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.PrecioUnitario, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.PrecioUnitario, new { htmlAttributes = new { @type = "number", @class = "form-control", @placeholder = "Ingrese el precio unitario de producto (no use decimales)...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.PrecioUnitario, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.UrlImange, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.UrlImange, new { htmlAttributes = new { @type = "url", @class = "form-control", @placeholder = "Ingrese la URL de imagen de producto..." } })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col-lg-12">
                                <input type="submit" style="margin-left:45%" class="btn btn-primary btn-success" name="Registrar" id="Registrar" value="Registrar" />
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>