Controllers/PedidosController.cs
using AccesoDatos;
using Entidades;
using PracticoMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticoMVC.Controllers
{
    public class PedidosController : Controller
    {
        // GET: Pedidos
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SelectCliente()
        {
            ClientesQuerys cq = new ClientesQuerys();
            List<Clientes> clientes = new List<Clientes>();
            clientes = cq.GetClientes();
            UsuariosQuerys uq = new UsuariosQuerys();
            List<Usuarios> usuarios = new List<Usuarios>();
            usuarios = uq.GetUsuarios();

            ViewBag.ListaClientes = clientes;
            ViewBag.ListaUsuarios = usuarios;

            return View();
        }

        [HttpPost]
        public ActionResult SelectCliente(PedidoBuscaClienteModelo modelo)
        {
            ClientesQuerys cq = new ClientesQuerys();
            List<Clientes> clientes = new List<Clientes>();
            Clientes entidad = new Clientes();
            entidad.RazonSocial = modelo.Cliente;
            clientes = cq.ClientePorNombre(entidad.RazonSocial);

            UsuariosQuerys uq = new UsuariosQuerys();
            List<Usuarios> usuarios = new List<Usuarios>();
            usuarios = uq.GetUsuarios();

            ViewBag.ListaClientes = clientes;
            ViewBag.ListaUsuarios = usuarios;

            return View();
        }

        [HttpGet]
        public ActionResult RegistroPedido(int codigo = 0)
        {
            PedidoModelo model = new PedidoModelo();
            Clientes entidad_c = new Clientes();
            List<Clientes> datosCliente = new List<Clientes>();
            entidad_c.Codigo = codigo;
            ClientesQuerys cq = new ClientesQuerys();
            datosCliente = cq.ClientePorCodigo(entidad_c.Codigo);

            foreach (var datos in datosCliente)
            {
                model.CodigoCliente = datos.Codigo;
                model.RazonSocialCliente = datos.RazonSocial;
            }

            PedidosQuerys pq = new PedidosQuerys();
            List<Pedidos> datosPedidos = new List<Pedidos>();
            datosPedidos = pq.UltimoPedido();
            int nuevoPedido = 0;
            foreach (var pedido in datosPedidos)
            {
                nuevoPedido = pedido.NumeroPedido + 1;
            }

            model.NumeroPedido = nuevoPedido;

            return View(model);
        }
    }
}

Views/Pedidos/RegistroPedido.cshtml
@model PracticoMVC.Models.PedidoModelo
@{DateTime fechaHora = DateTime.Now;}

@{
    ViewBag.Title = "Registro de Pedidos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        @if (ViewBag.Message != null)
        {
            <div class="row" style="margin-top:2%;">
                <div class="col-md-8">
                    <div class="@ViewBag.Class" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-lg-12">
                <button class="btn btn-primary btn-warning" title="Volver atrás" style="position: absolute; right: 0;" onclick='window.location="@Url.Action("SelectCliente","Pedidos")"' type="button"><i class="fas fa-arrow-alt-circle-left"></i></button>
                <br />
                <br />
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4> Registro de Pedidos </h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("RegistroPedido", "Pedidos", FormMethod.Post))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <br />
                        <h4>Datos de Cliente</h4>
                        <hr />
                        <div class="row form-group">
                            <div class="col col-md-2">
                                @Html.LabelFor(model => model.CodigoCliente, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col col-md-2">
                                @Html.EditorFor(model => model.CodigoCliente, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control", @placeholder = "Aquí debe autocompletarse el código de cliente...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.CodigoCliente, "", new { @class = "text-danger" })
                            </div>
                            <div class="col col-md-2">
                                @Html.LabelFor(model => model.RazonSocialCliente, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col col-md-6">
                                @Html.EditorFor(model => model.RazonSocialCliente, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control", @placeholder = "Aquí debe autocompletarse la razón social de cliente...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.RazonSocialCliente, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <h4>Datos de Pedido</h4>
                        <hr />
                        <div class="row form-group">
                            <div class="col col-md-2">
                                @Html.LabelFor(model => model.NumeroPedido, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col col-md-2">
                                @Html.EditorFor(model => model.NumeroPedido, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control", @placeholder = "X", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.NumeroPedido, "", new { @class = "text-danger" })
                            </div>
                            <div class="col col-md-2">
                                <span>Fecha y Hora</span>
                            </div>
                            <div class="col col-md-3">
                                <input type="text" class="form-control" name="FechaHoraActual" id="FechaHoraActual" value="@fechaHora" readonly="readonly" />
                            </div>
                        </div>
                        <h5>Detalle</h5>
                        <div class="row form-group">
                            <div class="col col-md-7">
                                <input type="text" class="form-control" name="ProductoBuscado" id="ProductoBuscado" />
                            </div>
                            <div>
                                <button class="btn btn-default btn-secondary" title="Buscar producto..." name="Buscar" id="Buscar" value="Buscar" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                        <br />
                        <br />
                        <div class="row form-group">
                            <div class="col-lg-12">
                                <input type="submit" style="margin-left:45%" class="btn btn-primary btn-success" name="Registrar" id="Registrar" value="Registrar" />
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

Views/Pedidos/SelectCliente.cshtml
@{int fila = 1; }
@model PracticoMVC.Models.PedidoBuscaClienteModelo

@{
    ViewBag.Title = "Pedidos - Selección de Cliente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .miActionLink:hover {
        color: white
    }

    .miActionLink {
        color: white
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <h3>Registro de Pedidos</h3>
        <hr />
        @using (Html.BeginForm("SelectCliente", "Pedidos", FormMethod.Post))
        {
            <div class="row form-group">
                <div class="col col-md-7">
                    @Html.EditorFor(model => model.Cliente, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese el nombre/razón social del cliente a buscar...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                </div>
                <div>
                    <button class="btn btn-default btn-secondary" title="Buscar cliente..." name="Buscar" id="Buscar" value="Buscar" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        }
        <br />
        <br />
        <div class="table-responsive">
            <h4> Listado de Clientes </h4>
            <hr />
            <table class="table table-borderless table-striped table-earning">
                <thead>
                    <tr style="text-align: center;">
                        <td> <b>#</b> </td>
                        <td> <b>Código</b> </td>
                        <td> <b>Razón Social</b> </td>
                        <td> <b>Usuario</b> </td>
                        <td> <b>Acción</b> </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.ListaClientes)
                    {
                        <tr style="text-align: center;">
                            <td>@fila</td>
                            <td>@item.Codigo </td>
                            <td>@item.RazonSocial </td>
                            @foreach (var usuario in ViewBag.ListaUsuarios)
                            {
                                if (item.IdUsuario == usuario.Id)
                                {
                                    <td>@usuario.Usuario</td>
                                }
                            }
                            <td>
                                <button title="Pedido" class="btn btn-primary btn-info" onclick='window.location="@Url.Action("RegistroPedido", "Pedidos", new { codigo = item.Codigo })"' type="button" name="Editar" id="Editar"><i class="fas fa-box"></i></button>
                            </td>
                        </tr>
                        fila++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-12">
        <button class="btn btn-primary btn-warning" title="Ir Hacia Arriba" style="position: absolute; right: 0;" type="button" onclick="topFunction()"><i class="fas fa-arrow-alt-circle-up"></i></button>
    </div>
</div>

<script>
    function topFunction() {
        document.body.scrollTop = 0; // For Safari
        document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
    }
</script>