Controllers/MarcasController.cs
using AccesoDatos;
using Entidades;
using PracticoMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticoMVC.Controllers
{
    public class MarcasController : Controller
    {
        // obtengo el listado de todas las marcas
        public ActionResult ConsultaMarcas()
        {
            MarcasQuerys mq = new MarcasQuerys();
            List<Marcas> marcas = new List<Marcas>();
            marcas = mq.GetMarcas();

            ViewBag.ListaMarcas = marcas;

            return View();
        }

        // preparo el formulario para registrar
        [HttpGet]
        public ActionResult RegistroMarca()
        {
            return View();
        }

        // valido el formulario para proceder al registro
        [HttpPost]
        public ActionResult RegistroMarca(MarcaModelo modelo)
        {
            int exito = 2; // es el valor cuando el modelo no es valido
            if(ModelState.IsValid) //si se cumplen todas las validaciones
            {
                try
                {
                    MarcasQuerys mq = new MarcasQuerys();
                    Marcas entidad = new Marcas();
                    entidad.Nombre = modelo.Nombre;
                    var existe = mq.ExisteNombre(entidad.Nombre); //busco la marca por nombre
                    if (existe == true) //si la marca ya existe
                    {
                        exito = 0;
                        ViewBag.Class = "alert alert-warning";
                        ViewBag.Message = "La marca que intenta registrar ya existe.";
                    }
                    else //si no existe, continuo con la inserción
                    {
                        var obj = mq.InsertMarca(entidad); //inserto la marca
                        if (obj == true) //si se pudo insertar
                        {
                            exito = 1;
                            ViewBag.Class = "alert alert-success";
                            ViewBag.Message = "Marca registrada correctamente!";
                        }
                        else //si no se pudo insertar, el error está en el método o la conexión a la DB
                        {
                            exito = 0;
                            ViewBag.Class = "alert alert-danger";
                            ViewBag.Message = "Oops! Algo ha ocurrido!";
                        }
                    }
                }
                catch (Exception e)
                {
                    throw e;
                }
            }

            //maneja la vista, según la variable éxito
            if (exito == 1)
            {
                ModelState.Clear();
                return View();
            }
            else
            {
                if (exito == 0)
                {
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    ViewBag.Class = "alert alert-warning";
                    ViewBag.Message = "Faltan datos por ingresar! Controle todos los campos que son obligatorios.";

                    return View(modelo);
                }
            }
        }

        // preparo el formulario para eliminar
        [HttpGet]
        public ActionResult EliminaMarca(int codigo = 0)
        {
            MarcaModelo model = new MarcaModelo();
            Marcas entidad = new Marcas();
            List<Marcas> datosMarca = new List<Marcas>();
            entidad.Id = codigo;
            MarcasQuerys mq = new MarcasQuerys();
            datosMarca = mq.MarcaPorCodigo(entidad.Id);

            foreach (var datos in datosMarca)
            {
                model.Id = datos.Id;
                model.Nombre = datos.Nombre;
            }

            return View(model);
        }

        // valido el formulario para proceder con la eliminación
        [HttpPost]
        public ActionResult EliminaMarca(MarcaModelo modelo)
        {
            int exito = 2; // es el valor cuando el modelo no es valido

            MarcasQuerys mq = new MarcasQuerys();

            if (ModelState.IsValid) //si se cumplen todas las validaciones
            {
                try
                {
                    Marcas entidad = new Marcas();
                    entidad.Id = modelo.Id;
                    var obj = mq.DeleteMarca(entidad.Id);
                    if (obj == true)
                    {
                        exito = 1;
                        ViewBag.Class = "alert alert-success";
                        ViewBag.Message = "Marca eliminada correctamente!";
                    }
                    else //si no se pudo eliminar, el error está en el método o la conexión a la DB
                    {
                        exito = 0;
                        ViewBag.Class = "alert alert-danger";
                        ViewBag.Message = "Oops! Algo ha ocurrido!";
                    }

                }
                catch (Exception e)
                {
                    throw e;
                }
            }

            //manejo la vista, según el valor de la variable exito
            if (exito == 1)
            {
                ModelState.Clear();
                return View();
            }
            else
            {
                if (exito == 0)
                {
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    ViewBag.Class = "alert alert-warning";
                    ViewBag.Message = "Faltan datos por ingresar! Controle todos los campos que son obligatorios.";

                    return View(modelo);
                }
            }
        }

        //preparo el formulario para la modificación
        [HttpGet]
        public ActionResult EditarMarca(int codigo = 0)
        {
            MarcaModelo model = new MarcaModelo();
            Marcas entidad = new Marcas();
            List<Marcas> datosMarca = new List<Marcas>();
            entidad.Id = codigo;
            MarcasQuerys mq = new MarcasQuerys();
            datosMarca = mq.MarcaPorCodigo(entidad.Id);

            foreach(var datos in datosMarca)
            {
                model.Id = datos.Id;
                model.Nombre = datos.Nombre;
            }

            return View(model);
        }

        //valido el formulario y procedo con la modificación
        [HttpPost]
        public ActionResult EditarMarca(MarcaModelo modelo)
        {
            int exito = 2; // es el valor cuando el modelo no es valido

            MarcasQuerys mq = new MarcasQuerys();

            if (ModelState.IsValid) //si se cumplen todas las validaciones
            {
                try
                {
                    Marcas entidad = new Marcas();
                    entidad.Id = modelo.Id;
                    entidad.Nombre = modelo.Nombre;
                    var obj = mq.UpdateMarca(entidad.Id,entidad.Nombre);
                    if (obj == true)
                    {
                        exito = 1;
                        ViewBag.Class = "alert alert-success";
                        ViewBag.Message = "Marca actualizada correctamente!";
                    }
                    else //si no se pudo eliminar, el error está en el método o la conexión a la DB
                    {
                        exito = 0;
                        ViewBag.Class = "alert alert-danger";
                        ViewBag.Message = "Oops! Algo ha ocurrido!";
                    }

                }
                catch (Exception e)
                {
                    throw e;
                }
            }

            //manejo la vista, según el valor de la variable exito
            if (exito == 1)
            {
                ModelState.Clear();
                return View();
            }
            else
            {
                if (exito == 0)
                {
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    ViewBag.Class = "alert alert-warning";
                    ViewBag.Message = "Faltan datos por ingresar! Controle todos los campos que son obligatorios.";

                    return View(modelo);
                }
            }
        }
    }
}

Controllers/RolesController.cs
using AccesoDatos;
using Entidades;
using PracticoMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticoMVC.Controllers
{
    public class RolesController : Controller
    {
        // GET: Roles
        public ActionResult ConsultaRoles()
        {
            RolesQuerys rq = new RolesQuerys();
            List<Roles> roles = new List<Roles>();
            roles = rq.GetRoles();

            ViewBag.ListaRoles = roles;

            return View();
        }

        // preparo el formulario para el registro de roles
        [HttpGet]
        public ActionResult RegistroRol()
        {
            return View();
        }

        // preparo el formulario para el registro de roles
        [HttpPost]
        public ActionResult RegistroRol(RolModelo modelo)
        {
            int exito = 2; // es el valor cuando el modelo no es valido
            if (ModelState.IsValid)
            {
                try
                {
                    RolesQuerys rq = new RolesQuerys();
                    Roles entidad = new Roles();
                    entidad.Id = modelo.Id;
                    entidad.Descripcion = modelo.Descripcion;
                    var existe = rq.ExisteNombre(entidad.Id,entidad.Descripcion); //busco el rol por descripcion
                    if (existe == true) //si la marca ya existe
                    {
                        exito = 0;
                        ViewBag.Class = "alert alert-warning";
                        ViewBag.Message = "El rol que intenta registrar ya existe.";
                    }
                    else //si no existe, continuo con la inserción
                    {
                        var obj = rq.InsertRol(entidad); //inserto la marca
                        if (obj == true) //si se pudo insertar
                        {
                            exito = 1;
                            ViewBag.Class = "alert alert-success";
                            ViewBag.Message = "Rol registrado correctamente!";
                        }
                        else //si no se pudo insertar, el error está en el método o la conexión a la DB
                        {
                            exito = 0;
                            ViewBag.Class = "alert alert-danger";
                            ViewBag.Message = "Oops! Algo ha ocurrido!";
                        }
                    }
                }
                catch (Exception e)
                {
                    throw e;
                }
            }

            //maneja la vista, según la variable éxito
            if (exito == 1)
            {
                ModelState.Clear();
                return View();
            }
            else
            {
                if (exito == 0)
                {
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    ViewBag.Class = "alert alert-warning";
                    ViewBag.Message = "Faltan datos por ingresar! Controle todos los campos que son obligatorios.";

                    return View(modelo);
                }
            }
        }

        // preparo el formulario para eliminar
        [HttpGet]
        public ActionResult EliminaRol(string codigo = "")
        {
            RolModelo model = new RolModelo();
            Roles entidad = new Roles();
            List<Roles> datosRol = new List<Roles>();
            entidad.Id = codigo;
            RolesQuerys rq = new RolesQuerys();
            datosRol = rq.RolPorCodigo(entidad.Id);

            foreach (var datos in datosRol)
            {
                model.Id = datos.Id;
                model.Descripcion = datos.Descripcion;
            }

            return View(model);
        }

        // valido el formulario para proceder con la eliminación
        [HttpPost]
        public ActionResult EliminaRol(RolModelo modelo)
        {
            int exito = 2; // es el valor cuando el modelo no es valido

            RolesQuerys rq = new RolesQuerys();

            if (ModelState.IsValid) //si se cumplen todas las validaciones
            {
                try
                {
                    Roles entidad = new Roles();
                    entidad.Id = modelo.Id;
                    var obj = rq.DeleteRol(entidad.Id);
                    if (obj == true)
                    {
                        exito = 1;
                        ViewBag.Class = "alert alert-success";
                        ViewBag.Message = "Rol eliminado correctamente!";
                    }
                    else //si no se pudo eliminar, el error está en el método o la conexión a la DB
                    {
                        exito = 0;
                        ViewBag.Class = "alert alert-danger";
                        ViewBag.Message = "Oops! Algo ha ocurrido!";
                    }

                }
                catch (Exception e)
                {
                    throw e;
                }
            }

            //manejo la vista, según el valor de la variable exito
            if (exito == 1)
            {
                ModelState.Clear();
                return View();
            }
            else
            {
                if (exito == 0)
                {
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    ViewBag.Class = "alert alert-warning";
                    ViewBag.Message = "Faltan datos por ingresar! Controle todos los campos que son obligatorios.";

                    return View(modelo);
                }
            }
        }

        [HttpGet]
        public ActionResult EditaRol(string codigo = "")
        {
            RolModelo model = new RolModelo();
            Roles entidad = new Roles();
            List<Roles> datosRol = new List<Roles>();
            entidad.Id = codigo;
            RolesQuerys rq = new RolesQuerys();
            datosRol = rq.RolPorCodigo(entidad.Id);

            foreach (var datos in datosRol)
            {
                model.Id = datos.Id;
                model.Descripcion = datos.Descripcion;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult EditaRol(RolModelo modelo)
        {
            int exito = 2; // es el valor cuando el modelo no es valido

            RolesQuerys rq = new RolesQuerys();

            if (ModelState.IsValid) //si se cumplen todas las validaciones
            {
                try
                {
                    Roles entidad = new Roles();
                    entidad.Id = modelo.Id;
                    entidad.Descripcion = modelo.Descripcion;
                    var obj = rq.UpdateRol(entidad.Id, entidad.Descripcion);
                    if (obj == true)
                    {
                        exito = 1;
                        ViewBag.Class = "alert alert-success";
                        ViewBag.Message = "Rol actualizado correctamente!";
                    }
                    else //si no se pudo eliminar, el error está en el método o la conexión a la DB
                    {
                        exito = 0;
                        ViewBag.Class = "alert alert-danger";
                        ViewBag.Message = "Oops! Algo ha ocurrido!";
                    }

                }
                catch (Exception e)
                {
                    throw e;
                }
            }

            //manejo la vista, según el valor de la variable exito
            if (exito == 1)
            {
                ModelState.Clear();
                return View();
            }
            else
            {
                if (exito == 0)
                {
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    ViewBag.Class = "alert alert-warning";
                    ViewBag.Message = "Faltan datos por ingresar! Controle todos los campos que son obligatorios.";

                    return View(modelo);
                }
            }
        }
    }
}

Views/Roles/ConsultaRoles.cshtml
@{int fila = 1; }

@{
    ViewBag.Title = "Consulta de Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .miActionLink:hover {
        color: white
    }

    .miActionLink {
        color: white
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <button class="btn btn-primary btn-success" title="Ingresar un elemento nuevo" style="position: absolute; right: 0;" type="button"><i class="fas fa-rub"></i> @Html.ActionLink("Nuevo", "RegistroRol", "Marcas", new { @class = "miActionLink" }) </button>
        <br />
        <div class="table-responsive">
            <h4> Listado de Roles </h4>
            <hr />
            <table class="table table-borderless table-striped table-earning">
                <thead>
                    <tr style="text-align: center;">
                        <td> <b>#</b> </td>
                        <td> <b>Código</b> </td>
                        <td> <b>Descripción</b> </td>
                        <td> <b>Acciones</b> </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.ListaRoles)
                    {
                        <tr style="text-align: center;">
                            <td>@fila</td>
                            <td>@item.Id </td>
                            <td>@item.Descripcion </td>
                            <td>
                                <button title="Editar" class="btn btn-primary btn-info" onclick='window.location="@Url.Action("EditaRol","Roles",new { codigo = item.Id })"' type="button" name="Editar" id="Editar"><i class="fas fa-edit"></i></button>
                                <button title="Eliminar" class="btn btn-primary btn-danger" onclick='window.location="@Url.Action("EliminaRol","Roles",new { codigo = item.Id })"' type="button" name="Eliminar" id="Elimiar"><i class="fas fa-crosshairs"></i></button>
                            </td>
                        </tr>
                        fila++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-12">
        <button class="btn btn-primary btn-warning" title="Ir Hacia Arriba" style="position: absolute; right: 0;" type="button" onclick="topFunction()"><i class="fas fa-arrow-alt-circle-up"></i></button>
    </div>
</div>

<script>
    function topFunction() {
        document.body.scrollTop = 0; // For Safari
        document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
    }
</script>

Views/Roles/EditaRol.cshtml
@model PracticoMVC.Models.RolModelo

@{
    ViewBag.Title = "Edición de Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        @if (ViewBag.Message != null)
        {
            <div class="row" style="margin-top:2%;">
                <div class="col-md-8">
                    <div class="@ViewBag.Class" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-lg-12">
                <button class="btn btn-primary btn-warning" title="Volver atrás" style="position: absolute; right: 0;" onclick='window.location="@Url.Action("ConsultaRoles","Roles")"' type="button"><i class="fas fa-arrow-alt-circle-left"></i></button>
                <br />
                <br />
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4> Edición de Roles </h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("EditaRol", "Roles", FormMethod.Post))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese el código del rol...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese la descripción del rol...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col-lg-12">
                                <input type="submit" style="margin-left:45%" class="btn btn-primary" name="Modificar" id="Modificar" value="Modificar" />
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

Views/Roles/EliminaRol.cshtml
@model PracticoMVC.Models.RolModelo

@{
    ViewBag.Title = "Eliminiación de Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        @if (ViewBag.Message != null)
        {
            <div class="row" style="margin-top:2%;">
                <div class="col-md-8">
                    <div class="@ViewBag.Class" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-lg-12">
                <button class="btn btn-primary btn-warning" title="Volver atrás" style="position: absolute; right: 0;" onclick='window.location="@Url.Action("ConsultaRoles","Roles")"' type="button"><i class="fas fa-arrow-alt-circle-left"></i></button>
                <br />
                <br />
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4> Eliminación de Roles </h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("EliminaRol", "Roles", FormMethod.Post))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese el código del rol...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese la descripción del rol...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col-lg-12">
                                <input type="submit" style="margin-left:45%" class="btn btn-primary btn-danger" name="Eliminar" id="Eliminar" value="Eliminar" />
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

Views/Roles/RegistroRol.cshtml
@model PracticoMVC.Models.RolModelo

@{
    ViewBag.Title = "Registro de Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        @if (ViewBag.Message != null)
        {
            <div class="row" style="margin-top:2%;">
                <div class="col-md-8">
                    <div class="@ViewBag.Class" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-lg-12">
                <button class="btn btn-primary btn-warning" title="Volver atrás" style="position: absolute; right: 0;" onclick='window.location="@Url.Action("ConsultaRoles","Roles")"' type="button"><i class="fas fa-arrow-alt-circle-left"></i></button>
                <br />
                <br />
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4> Registro de Roles </h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("RegistroRol", "Roles", FormMethod.Post))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <br />
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese el código del rol...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "form-control-label" })
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese la descripción del rol...", @style = "text-transform:uppercase;", @onkeyup = "javascript:this.value=this.value.toUpperCase()" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="row form-group">
                            <div class="col-lg-12">
                                <input type="submit" style="margin-left:45%" class="btn btn-primary btn-success" name="Registrar" id="Registrar" value="Registrar" />
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>